import Footer from "@/components/footer";
import "./globals.css";
import Sidebar from "@/components/sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className={`flex flex-col antialiased`}>
        <div className="wrapper min-h-full grid grid-rows-[auto_1fr_auto]">
          <Sidebar />
          <main>{children}</main>
          <Footer />  
        </div>
      </body>
    </html>
  );
}
